{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "imageclassifier.serviceAccountName" . }}
  labels:
{{ include "imageclassifier.labels" . | nindent 4 }}
{{- end -}}
