apiVersion: v1
kind: Secret
metadata:
  name: fruit-secret
type: Opaque
data:
  azurestorageaccountkey: {{ default "" .Values.worker.azurestorageaccountkey | b64enc | quote }}
  azurestorageaccountname: {{ default "" .Values.worker.azurestorageaccountname | b64enc | quote }}
